INSERT INTO `ipar4v2`.`nodes`
(`id`, `type`, `position`, `content`, `image_link`, `video_link`, `next`, `machine_type`, `is_leaf`)
VALUES
(20, 'R', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(21, 'I', '1.1', 'Ellenőrizze a PLC-nél a szenzorok bekötését!', 'na', 'na', '', 3, false),
(22, 'Q', '1.1', 'A melléklet alapján megfelelően világítanak a ledek a PLC inputjainál?', 'na', 'na', 'Nem	1.1.1	Igen	1.1.2', 3, false),
(23, 'I', '1.1.1', 'Igazítsa meg a kábeleket a PLC inputjainál!', 'na', 'na', '', 3, false),
(24, 'Q', '1.1.1', 'Megoldódott a probléma?', 'na', 'na', 'Igen	1.1.1.1	Nem	1.1.1.2', 3, false),
(25, 'S', '1.1.1.1', 'A kábelek megigazítása megoldotta a problémát.', 'na', 'na', '', 3, true),
(26, 'B', '1.1.1.2', 'A kábelek megigazítása nem oldotta meg a problémát, másik ágra áttérés!', 'na', 'na', '1.2', 3, true),
(27, 'B', '1.1.2', 'Nem a bekötéssel van a probléma, másik ágra áttérés!', 'na', 'na', '1.2', 3, true),
(28, 'I', '1.2', 'Ellenőrizze, hogy a szenzorok talapzata megfelelően van-e rögzítve!', 'na', 'na', '', 3, false),
(29, 'Q', '1.2', 'A szenzorok talapzata az aljazba megfelelően van bedugva?', 'na', 'na', 'Nem	1.2.1	Igen	1.2.2', 3, false),
(30, 'I', '1.2.1', 'Helyezze a foglalatba a talapzatot!', 'na', 'na', '', 3, false),
(31, 'Q', '1.2.1', 'Megoldódott a probléma?', 'na', 'na', 'Igen	1.2.1.1	Nem	1.2.1.2', 3, false),
(32, 'S', '1.2.1.1', 'A talapzat a foglalatba helyezéssel megoldotta a problémát.', 'na', 'na', '', 3, true),
(33, 'B', '1.2.1.2', 'A talapzat a foglalatba helyezéssel nem oldotta meg a problémát, másik ágra áttérés!', 'na', 'na', '1.3', 3, true),
(34, 'B', '1.2.2', 'Nem a talapzattal van probléma, másik ágra áttérés!', 'na', 'na', '1.3', 3, true),
(35, 'I', '1.3', 'Ellenőrizze, hogy a korong elég közel került-e a szenzorokhoz! Figyelje a PLC hátulján a szenzorokhoz tartozó ledeket!', 'na', 'na', '', 3, false),
(36, 'Q', '1.3', 'Az érzékeléskor változik a szenzorokhoz tartozó ledek állása?', 'na', 'na', 'Nem	1.3.1	Igen	1.3.2', 3, false),
(37, 'I', '1.3.1', 'Ellenőrizze kézzel a szenzorokhoz való korong közelítéssel, a melléklet alapján, azok megfelelő működését!', 'na', 'na', '', 3, false),
(38, 'Q', '1.3.1', 'Változik a ledek állása?', 'na', 'na', 'Nem mindnél	1.3.1.1	Igen	1.3.2', 3, false),
(39, 'I', '1.3.1.1', 'Figyelje meg alaposan, és jegyezze fel, melyek esetén nem, hangsúlyosan a színérzékelő vonatkozásában.', 'na', 'na', '', 3, false),
(40, 'Q', '1.3.1.1', 'A színérzékelő megfelelően működött?', 'na', 'na', 'Igen	1.3.1.1.1	Nem	1.3.1.1.2', 3, false),
(41, 'I', '1.3.1.1.1', 'A feljegyzett szenzor(ok) kicserélésére lesz szükség!', 'na', 'na', '', 3, false),
(42, 'Q', '1.3.1.1.1', 'Megoldódott a probléma?', 'na', 'na', 'Igen	1.3.1.1.1.1	Nem	1.3.1.1.1.2', 3, false),
(43, 'S', '1.3.1.1.1.1', 'A szenzor(ok) cseréje megoldotta a problémát.', 'na', 'na', '', 3, true),
(44, 'B', '1.3.1.1.1.2', 'Nem a szenzorokkal van probléma, másik ágra áttérés!', 'na', 'na', '1.4', 3, true),
(45, 'I', '1.3.2', 'Figyelje meg a megfogóban a korongot.', 'na', 'na', '', 3, false),
(46, 'Q', '1.3.2', 'Ingatag a korong megfogása?', 'na', 'na', 'Igen	1.3.2.1	Nem	1.3.2.2', 3, false),
(47, 'I', '1.3.2.1', 'Ellenőrizze, hogy a korong paraméterei megfelelőek-e a melléklet alapján, és amennyiben nem, távolítsa el!', 'na', 'na', '', 3, false),
(48, 'Q', '1.3.2.1', 'Továbbra is ingatag a korong megfogása?', 'na', 'na', 'Igen	1.3.2.1.1	Nem	1.3.2.1.1', 3, false),
(49, 'I', '1.3.2.1.1', 'Ellenőrizze, hogy a megfogóhoz tartozó pneumatikus rendszer megfelelően működik-e a melléklet alapján!', 'na', 'na', '', 3, false),
(50, 'Q', '1.3.2.1.1', 'Továbbra is ingatag a korong megfogása?', 'na', 'na', 'Igen	1.3.2.1.1.1	Nem	1.3.2.1.2', 3, false),
(51, 'I', '1.3.1.1.2', 'Ellenőrizze a színérzékelő körül a megvilágítást (például: nincs-e árnyékban, nincs-e más fényforrásnak torzító hatása)', 'na', 'na', '', 3, false),
(52, 'Q', '1.3.1.1.2', 'Befolyásolhatja a környezeti megvilágítás a szenzor működését?', 'na', 'na', 'Igen	1.3.1.1.2.1	Nem	1.3.1.1.1', 3, false),
(53, 'I', '1.3.1.1.2.1', 'Szüntesse meg a vélt zavar forrását, és ellenőrizze újból a színérzékelő működését, amíg nem marad feltételezett hibaok.', 'na', 'na', '', 3, false),
(54, 'Q', '1.3.1.1.2.1', 'Megoldódott a probléma?', 'na', 'na', 'Igen	1.3.1.1.2.1.1	Nem	1.3.1.1.2.1.2', 3, false),
(55, 'S', '1.3.1.1.2.1.1', 'A környezeti befolyás megszüntetése megoldotta a problémát.', 'na', 'na', '', 3, true),
(56, 'B', '1.3.1.1.2.1.2', 'A környezeti befolyás megszüntetése nem oldotta meg a problémát, másik ágra áttérés!', 'na', 'na', '1.4', 3, true),
(57, 'I', '1.3.2.1.1.1', 'Húzza meg a fogót rögzítő csavarokat vagy cserélje le a fogó fejet!', 'na', 'na', '', 3, false),
(58, 'Q', '1.3.2.1.1.1', 'Megoldódott a probléma?', 'na', 'na', 'Igen	1.3.2.1.1.1.1	Nem	1.3.2.1.1.1.2', 3, false),
(59, 'S', '1.3.2.1.1.1.1', 'A fogó fejének javítása megoldotta a problémát.', 'na', 'na', '', 3, true),
(60, 'B', '1.3.2.1.1.1.2', 'A fogó fej javítása nem oldotta meg a problémát, másik ágra áttérés!', 'na', 'na', '1.4', 3, true),
(61, 'I', '1.3.2.1.2', 'Tesztelje a munkamenetet, figyelje meg, hogy fent áll-e még a probléma.', 'na', 'na', '', 3, false),
(62, 'Q', '1.3.2.1.2', 'Megoldódott a probléma?', 'na', 'na', 'Igen	1.3.2.1.2.1	Nem	1.3.2.1.2.2', 3, false),
(63, 'S', '1.3.2.1.2.1', 'Sikeres hibajavítás, a probléma elhárult.', 'na', 'na', '', 3, true),
(64, 'B', '1.3.2.1.2.2', 'Nem sikerült a hibát kijavítani, másik ágra áttérés!', 'na', 'na', '1.4', 3, true),
(65, 'B', '1.3.2.2', 'Nem a fogással van probléma, másik ágra áttérés!', 'na', 'na', '1.4', 3, true),
(66, 'E', '1.4', 'Amennyiben a hiba továbbra is fenn áll, a FaultAssist rendszerben nem lekezelt eset áll fent: forduljon szakértőhöz.', 'na', 'na', '', 3, true),

(67, 'R', '2', 'Sikertelen elindítás', 'na', 'na', '', 3, false),
(68, 'I', '2.1', 'Ellenőrizze a melléklet alapján, hogy megfelelően van-e a rendszer összekötve!', 'http://vm.ik.bme.hu:5631/ipar4/images/osszekotes.png', 'na', '', 3, false),
(69, 'Q', '2.1', 'Megfelelően van összekötve?', 'na', 'na', 'Nem	2.1.1	Igen	2.1.2', 3, false),
(70, 'I', '2.1.1', 'A melléklet alapján kösse össze!', 'http://vm.ik.bme.hu:5631/ipar4/images/osszekotes.png', 'na', '', 3, false),
(71, 'Q', '2.1.1', 'Megoldódott a probléma?', 'na', 'na', 'Igen	2.1.1.1	Nem	2.1.1.2', 3, false),
(72, 'S', '2.1.1.1', 'Megfelelő összekötéssel megoldódott a probléma.', 'na', 'na', '', 3, true),
(73, 'B', '2.1.1.2', 'Megfelelő összekötés nem oldotta meg a hibát, másik ágra áttérés!', 'na', 'na', '2.2', 3, true),
(74, 'B', '2.1.2', 'Nem az összekötéssel van a probléma, másik ágra áttérés!', 'na', 'na', '2.2', 3, true),
(75, 'I', '2.2', 'Ellenőrizze, hogy a teljesítmény elektronikán "manual"-ra legyen állítva a kulcsos kapcsoló!', 'na', 'na', '', 3, false),
(76, 'Q', '2.2', 'Megoldódott a probléma?', 'na', 'na', 'Igen	2.2.1	Nem	2.2.2', 3, false),
(77, 'S', '2.2.1', 'A kapcsoló állítása sikeresen megoldotta a problémát.', 'na', 'na', '', 3, true),
(78, 'B', '2.2.2', 'A kapcsoló állítása nem oldotta meg a problémát, másik ágra áttérés!', 'na', 'na', '2.3', 3, true),
(79, 'I', '2.3', 'Ellenőrizze, hogy a betanító pulton a "teack" gomb be van-e nyomva, ha igen, akkor "nyomja ki"!', 'na', 'na', '', 3, false),
(80, 'Q', '2.3', 'Megoldódott a probléma?', 'na', 'na', 'Igen	2.3.1	Nem	2.3.2', 3, false),
(81, 'S', '2.3.1', 'A gomb kinyomásával megoldódott a probléma.', 'na', 'na', '', 3, true),
(82, 'B', '2.3.2', 'A gomb kinyomásával nem oldódott meg a probléma, másik ágra áttérés!', 'na', 'na', '2.4', 3, true),
(83, 'E', '2.4', 'Amennyiben a hiba továbbra is fenn áll, a FaultAssist rendszerben nem lekezelt eset áll fent: forduljon szakértőhöz.', 'na', 'na', '', 3, false),

(84, 'R', '3', 'Sikertelen megfogás', 'na', 'na', '', 3, false),
(85, 'I', '3.1', 'Ellenőrizze, hogy megfelelő pozícióban próbálja-e megfogni a korongot!', 'na', 'na', '', 3, false),
(86, 'Q', '3.1', 'Jó helyen van a megfogó?', 'na', 'na', 'Nem	3.1.1	Igen	3.1.2', 3, false),
(87, 'I', '3.1.1', 'Ellenőrizze, hogy megfelelő orientációban van-e a korong tároló!', 'na', 'na', '', 3, false),
(88, 'Q', '3.1.1', 'Jó irányban áll?', 'na', 'na', 'Nem	3.1.1.1	Igen	3.1.1.2', 3, false),
--nincs kész
(89, 'I', '3.1.1.1', '', 'na', 'na', '', 3, false),
(90, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(91, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(92, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(93, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(94, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(95, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(96, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(97, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(98, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(99, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(100, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(101, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(102, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(103, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(104, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(105, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(106, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(107, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(108, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(109, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(110, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(111, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(112, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(113, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(114, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(115, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(116, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(117, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(118, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false),
(119, 'B', '1', 'Hibás érzékelés', 'na', 'na', '', 3, false);